# -*- coding: utf-8 -*-
"""text-to-speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxhM9Kha2M_Hs5WrRCns3tu0KGofWMj8
"""

!pip install transformers

from transformers import pipeline

text = "I am learning generative ai"

pipe = pipeline("text-to-speech", model="suno/bark-small", device="cuda")

output = pipe(text)

output

from IPython.display import Audio

Audio(output["audio"], rate=output["sampling_rate"])

!pip uninstall -y transformers
!pip install git+https://github.com/huggingface/transformers.git

from transformers import pipeline

text = "I am learning new technology generative ai"

pipe = pipeline("text-to-speech", model="facebook/mms-tts-eng", device="cuda")

out = pipe(text)

from IPython.display import Audio

Audio(out["audio"], rate=out["sampling_rate"])

